version: "3.7"

services:
  # image project
  app:
    build:
      args:
        user: clinica
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: clinica/laravel
    container_name: clinica-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - clinica-med

  # nginx
  nginx:
    container_name: clinica-nginx
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d/
    networks:
      - clinica-med

  # db mysql
  db:
    image: mysql:5.7
    container_name: clinica-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - "3388:3306"
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - clinica-med

networks:
  clinica-med:
    driver: bridge
